IM_SIZE = 45

# Neural Network config
CONV_FILTERS = [32, 48]
CONV_KERNEL_SIZES = [6, 5]
CONV_STRIDES = [2, 2]
CONTEXT_SIZE = 256
DUELING_DEPTH = 3
DUELING_LAYER_SIZE = 256
ACTOR_FC_DEPTH = 3
ACTOR_FC_SIZE = 256

ACTION_CONC = True
ACTION_INPUT_EMBD = True
WEIGHT_INPUT_EMBD = True

DENSE_INIT = 'glorot_uniform'
L_ALPHA = 0.01
CLIPPING_LOSS_RATIO = 0.2
ENTROPY_LOSS_RATIO = 5e-3

BLACK_AND_WHITE = False
